### ISSUE TITLE
Can't access official page

### ISSUE THREAD

**Issue by feel-the-dz3n** [rgimad/EOS#1]
https://vk.com/eos_developer_notes is blocked in my country. Are there any mirrors? Thanks.

**Comment by ItsMoonPy** [comment]
используй впн @feel-the-dz3n

**Comment by gimadutdin** [comment]
feel-the-dz3n , Maybe you will can open it using Tor Browser

**Comment by feel-the-dz3n** [comment]
What the fuck. Am I a hacker to you? I want to use my Google Chrome.
